# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-02 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_maps', '0002_auto_20160802_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='height',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='objectX',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='objectY',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='objects',
            name='width',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='objects',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
