# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-08-25 06:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('object_maps', '0003_auto_20160802_1558'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='objects',
            new_name='obstacle',
        ),
        migrations.RenameField(
            model_name='obstacle',
            old_name='objectX',
            new_name='obstacleX',
        ),
        migrations.RenameField(
            model_name='obstacle',
            old_name='objectY',
            new_name='obstacleY',
        ),
    ]
