# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:21
from __future__ import unicode_literals

import django.core.serializers.json
from django.db import migrations, models
import django_pgjsonb.fields
import location_field.models.plain


class Migration(migrations.Migration):

    dependencies = [
        ('object_maps', '0005_auto_20160906_1734'),
    ]

    operations = [
        migrations.CreateModel(
            name='Body',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('DataSequence', django_pgjsonb.fields.JSONField(decode_kwargs={}, encode_kwargs={'cls': django.core.serializers.json.DjangoJSONEncoder})),
            ],
        ),
        migrations.CreateModel(
            name='Head',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Time', models.DateTimeField()),
                ('location', location_field.models.plain.PlainLocationField(max_length=63)),
            ],
        ),
        migrations.CreateModel(
            name='Tail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.TextField()),
                ('Accuracy', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='objects',
            name='dis',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='height',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='objectX',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='objectY',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='reliability',
        ),
        migrations.RemoveField(
            model_name='objects',
            name='width',
        ),
        migrations.AlterField(
            model_name='objects',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
