# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-15 06:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('object_maps', '0006_auto_20170315_1521'),
    ]

    operations = [
        migrations.AddField(
            model_name='objects',
            name='Time1',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='head',
            name='Time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
